# Generated by Django 3.2.3 on 2022-06-25 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('usn', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=200)),
                ('team_size', models.IntegerField()),
                ('student1_usn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student1_usn', to='smartForm.student')),
                ('student2_usn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student2_usn', to='smartForm.student')),
                ('student3_usn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student3_usn', to='smartForm.student')),
            ],
        ),
    ]
