# Generated by Django 3.2.3 on 2022-06-26 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartForm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='student3_usn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student3_usn', to='smartForm.student'),
        ),
    ]
